version: '3'

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${PD_PASSWORD}
      POSTGRES_DB: ${PD_NAMEDB}
    container_name: proyectsdb
    volumes:
      - ./postgres:/var/lib/postgresql/data
